### ISSUE TITLE
How to submit the prediction files on testing sets?

### ISSUE THREAD

**Issue by cardwing** [karstenBehrendt/benchmarks_website#1]
@karstenBehrendt Thanks for your efforts to release the LLAMAS dataset. It will contribute a lot to the research community in autonomous driving fields. However, I wonder how I can submit the prediction files on testing sets. I did not find any button that can support the submission. Thanks in advance.

**Comment by karstenBehrendt** [comment]
Hi @cardwing - I will try to add a submission functionality on Sunday, August 11. Since submissions can contain semantic segmentation for about 20,000 images, the files will be fairly large and I haven't yet checked how I will handle that including backups. I also didn't expect submissions this early. 

So, I'm aiming for Sunday and it may take a few days for the evaluation script to run on the submissions.

**Comment by cardwing** [comment]
Thanks for your response. Looking forward to the submission function. ^_^

**Comment by cardwing** [comment]
@karstenBehrendt I have tested the evaluation script on the validation set and it runs well.

**Comment by karstenBehrendt** [comment]
The submission script is now added as part of 517dee2 
I hope everything works. At the moment, evaluations and notifications are not automated.
